"""DB setup

Revision ID: 04ede4e55d57
Revises: 
Create Date: 2022-08-12 08:24:02.810769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ede4e55d57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etudiants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('adresse', sa.String(length=200), nullable=True),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etudiants')
    op.drop_table('filieres')
    # ### end Alembic commands ###
